import HealthKit
import SwiftUI

/// Detail view for one workout. Header carries the name, scheduled
/// date, status chip, and description; the block list shows each
/// planned block in order with its completion state. Tapping a
/// block's status chip opens a menu to mark it pending/done/skipped.
///
/// The workout loads via `WorkoutStore.detail(id:)` (cached, so
/// returning from the editor is instant and already fresh —
/// `update` rewrites the cache). Edit opens the editor sheet;
/// delete confirms then pops back to the list. The "Logged sets"
/// section lists everything logged against the workout (grouped
/// under their blocks, collapsed) with swipe-to-edit and delete —
/// the same row actions as the per-exercise history screen.
struct WorkoutDetailView: View {
    @EnvironmentObject private var env: AppEnvironment
    @EnvironmentObject private var authStore: AuthStore
    @Environment(\.dismiss) private var dismiss
    @ObservedObject var store: WorkoutStore
    @ObservedObject var blockStore: BlockStore

    let workoutID: String

    @State private var showingEditor: Bool = false
    @State private var showingDuplicate: Bool = false
    @State private var showingDelete: Bool = false
    /// Player presentation request. `Identifiable` (fresh UUID per
    /// tap) so every Start opens a new player instance with a fresh
    /// fetch — re-presenting must never reuse a stale session whose
    /// join IDs were regenerated by an intervening workout edit.
    @State private var playerRequest: PlayerRequest?
    @State private var didRequestLoad: Bool = false
    /// Sets logged against this workout, for the history section.
    /// Loaded with the detail and reloaded whenever the player
    /// closes (the player is where entries change).
    @State private var loggedEntries: [ExerciseEntryDTO] = []
    @State private var entriesLoaded: Bool = false
    /// History group names expanded by the user. Empty (the
    /// default) means every group starts collapsed.
    @State private var expandedHistoryGroups: Set<String> = []
    /// Entry under edit in the history section (`EditSetView`
    /// sheet) or pending delete confirmation.
    @State private var editingEntry: ExerciseEntryDTO?
    @State private var entryPendingDelete: ExerciseEntryDTO?
    @State private var showingEntryDeleteConfirm: Bool = false
    /// Entry ids with a delete request in flight (row spinners).
    @State private var deletingEntryIDs: Set<String> = []
    /// Entry-operation error, rendered as a row at the top of
    /// the history section (kept separate from the store error
    /// slot so entry failures can't clobber workout errors).
    @State private var entriesError: String?

    private struct PlayerRequest: Identifiable {
        let id = UUID()
        let workoutID: String
    }

    private var workout: WorkoutDTO? {
        store.details[workoutID]
    }

    var body: some View {
        content
            .navigationTitle(workout?.name ?? "Workout")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                if workout != nil {
                    ToolbarItem(placement: .topBarTrailing) {
                        Button("Edit") { showingEditor = true }
                    }
                }
            }
            .sheet(isPresented: $showingEditor) {
                if let workout {
                    WorkoutEditorView(
                        mode: .edit(workout),
                        store: store,
                        blockStore: blockStore
                    )
                    .environmentObject(env)
                }
            }
            .sheet(isPresented: $showingDuplicate) {
                if let workout {
                    WorkoutDuplicateSheet(
                        workout: workout,
                        store: store,
                        onDuplicated: { _ in
                            // The sheet dismisses itself first; then pop
                            // back to the list where the new copy is
                            // visible. (The list's own duplicate flow
                            // pushes the new detail instead — both end
                            // somewhere sensible.)
                            dismiss()
                        },
                        onBatchDuplicated: {
                            // Same landing as a one-off: back to the
                            // list, which already merged the new rows.
                            dismiss()
                        }
                    )
                    .environmentObject(env)
                }
            }
            .alert("Delete this workout?", isPresented: $showingDelete) {
                Button("Delete", role: .destructive) {
                    Task {
                        await store.delete(id: workoutID)
                        if store.errorMessage == nil {
                            dismiss()
                        }
                    }
                }
                Button("Cancel", role: .cancel) {}
            } message: {
                Text("This permanently removes the workout and its plan. Logged sets are unaffected.")
            }
            // History entry sheet + delete confirmation live at
            // root level (not on the History section): sheets
            // attached inside a List section can drop on list
            // updates — the flash-open-then-close bug. Every
            // other sheet in this view already lives here.
            .sheet(item: $editingEntry) { entry in
                EditSetView(exerciseEntry: entry) { updated in
                    loggedEntries = loggedEntries.map { $0.id == updated.id ? updated : $0 }
                }
                .environmentObject(env)
                .environmentObject(authStore)
            }
            .alert(
                (entryPendingDelete?.isCardio ?? false) ? "Delete this session?" : "Delete this set?",
                isPresented: $showingEntryDeleteConfirm,
                presenting: entryPendingDelete
            ) { entry in
                Button("Delete", role: .destructive) {
                    Task { await deleteEntry(entry) }
                }
                Button("Cancel", role: .cancel) {}
            } message: { entry in
                Text(entry.isCardio
                    ? "This will permanently remove the session from this workout's history."
                    : "This will permanently remove the set from this workout's history.")
            }
            .fullScreenCover(item: $playerRequest) { request in
                WorkoutPlayerView(
                    workoutID: request.workoutID,
                    workoutStore: store,
                    player: WorkoutPlayerStore(
                        workoutID: request.workoutID,
                        api: env.api,
                        weightUnit: authStore.currentUser?.weightUnit ?? "kg",
                        distanceUnit: authStore.currentUser?.distanceUnit ?? "km"
                    )
                )
                .environmentObject(env)
                .environmentObject(authStore)
            }
            .task {
                guard !didRequestLoad else { return }
                didRequestLoad = true
                await store.detail(id: workoutID)
                await loadEntries()
            }
            .onChange(of: playerRequest != nil) { _, isOpen in
                // The player is where entries change — refresh
                // the history section on every close. (Opening
                // fires this too; the guard skips that half.)
                if !isOpen {
                    Task { await loadEntries() }
                }
            }
    }

    @ViewBuilder
    private var content: some View {
        if let workout {
            loadedView(workout)
        } else if let error = store.errorMessage {
            VStack(spacing: DSSpacing.md) {
                Image(systemName: Icons.warning)
                    .font(.largeTitle)
                    .foregroundStyle(DSColors.destructive)
                Text(error)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(DSColors.textSecondary)
                Button("Try again") {
                    Task { await store.detail(id: workoutID, refresh: true) }
                }
                .buttonStyle(.dsSecondary)
            }
            .padding(DSSpacing.lg)
            .frame(maxWidth: .infinity, maxHeight: .infinity)
        } else {
            ProgressView()
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
    }

    private func loadedView(_ workout: WorkoutDTO) -> some View {
        List {
            Section {
                HStack(spacing: DSSpacing.xs) {
                    Text(WorkoutDates.display(workout.scheduledDate))
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(DSColors.text)
                    Text("·")
                        .foregroundStyle(DSColors.textSecondary)
                    Text(workout.status.displayName)
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(DSColors.accent)
                    Spacer()
                    Text(workout.progressLabel)
                        .font(.subheadline)
                        .foregroundStyle(DSColors.textSecondary)
                }
                if !workout.description.isEmpty {
                    Text(workout.description)
                        .font(.body)
                        .foregroundStyle(DSColors.text)
                }
                Picker("Status", selection: statusBinding(for: workout)) {
                    ForEach(WorkoutStatusDTO.allCases, id: \.self) { status in
                        Text(status.displayName).tag(status)
                    }
                }
                // Apple Health activity type: menu writes through
                // the type-only PATCH endpoint so block check-offs
                // survive (the editor's PUT would reset them).
                // Unknown/missing keys read as the blanket default.
                Menu {
                    ForEach(WorkoutHealthActivityMapper.selectableTypes, id: \.rawValue) { type in
                        Button {
                            Task {
                                await store.setHealthActivityType(
                                    id: workout.id,
                                    healthActivityType: WorkoutHealthActivityMapper.key(for: type)
                                )
                            }
                        } label: {
                            Label(
                                WorkoutHealthActivityMapper.displayName(for: type),
                                systemImage: resolvedHealthActivityType(for: workout) == type ? "checkmark" : "circle"
                            )
                        }
                    }
                } label: {
                    HStack {
                        Text("Activity type")
                            .foregroundStyle(DSColors.textSecondary)
                        Spacer()
                        Text(WorkoutHealthActivityMapper.displayName(for: resolvedHealthActivityType(for: workout)))
                            .foregroundStyle(DSColors.text)
                    }
                }
                .buttonStyle(.plain)
                .accessibilityLabel("Apple Health activity type")
            }

            // Primary entry to the Workout Player: full-screen
            // session that walks through every block, logging sets
            // as exercise entries. "Start" is UI state only — the
            // workout flips to in_progress on the first logged set.
            // Hidden once the workout is completed or skipped (the
            // status picker above reopens it when more logging is
            // needed). Deliberately chromeless — no card
            // background, tight insets — so the button sits close
            // to the sections around it instead of floating in its
            // own card like Duplicate/Delete below.
            if workout.status == .planned || workout.status == .inProgress {
                Section {
                    Button {
                        playerRequest = PlayerRequest(workoutID: workout.id)
                    } label: {
                        Text(workout.status == .inProgress ? "Resume workout" : "Start workout")
                    }
                    .buttonStyle(.dsPrimary)
                    .listRowBackground(Color.clear)
                    .listRowInsets(EdgeInsets(
                        top: DSSpacing.xxs,
                        leading: DSSpacing.md,
                        bottom: DSSpacing.xxs,
                        trailing: DSSpacing.md
                    ))
                    .listRowSeparator(.hidden)
                }
            }

            Section {
                ForEach(workout.blocks) { block in
                    HStack(alignment: .top, spacing: DSSpacing.sm) {
                        VStack(alignment: .leading, spacing: 2) {
                            Text(block.blockName)
                                .font(.body)
                                .foregroundStyle(DSColors.text)
                            Text(blockSubtitle(for: block))
                                .font(.subheadline)
                                .foregroundStyle(DSColors.textSecondary)
                        }
                        Spacer()
                        Menu {
                            ForEach(WorkoutBlockStatusDTO.allCases, id: \.self) { status in
                                Button {
                                    Task {
                                        await store.setBlockStatus(
                                            workoutID: workout.id,
                                            workoutBlockID: block.id,
                                            status: status
                                        )
                                    }
                                } label: {
                                    Label(
                                        status.displayName,
                                        systemImage: block.status == status ? "checkmark" : statusIcon(for: status)
                                    )
                                }
                            }
                        } label: {
                            // Secondary badge chrome (inverted fill +
                            // on-color text, mirroring the player and
                            // the cardio type pill) — the status
                            // reads from the label, not from colour.
                            Text(block.status.displayName)
                                .font(.caption.weight(.semibold))
                                .padding(.horizontal, DSSpacing.sm)
                                .padding(.vertical, DSSpacing.xxs + 2)
                                .background(
                                    Capsule().fill(DSColors.secondary)
                                )
                                .foregroundStyle(DSColors.onSecondary)
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel("Mark \(block.blockName) \(block.status.displayName)")
                    }
                    .padding(.vertical, DSSpacing.xxs)
                }
            } header: {
                Text("Blocks")
            }

            // History of everything logged against this workout
            // (player sessions, including reopens), grouped under
            // their planned blocks — every group collapsed by
            // default. Rows carry the history screen's swipe
            // actions: leading swipe edits via `EditSetView`,
            // trailing swipe deletes behind a confirmation.
            // Grouping recomputes from `loggedEntries`, so edited
            // rows move themselves and emptied groups vanish.
            if entriesLoaded {
                Section("History") {
                    if let entriesError {
                        Text(entriesError)
                            .font(.footnote)
                            .foregroundStyle(DSColors.destructive)
                    }
                    let groups = Self.groupedEntries(blocks: workout.blocks, entries: loggedEntries)
                    if groups.isEmpty {
                        Text("No sets logged yet — start the workout to log your first set.")
                            .font(.footnote)
                            .foregroundStyle(DSColors.textSecondary)
                    } else {
                        ForEach(Array(groups.enumerated()), id: \.offset) { _, group in
                            DisclosureGroup(isExpanded: historyGroupBinding(for: group.name)) {
                                ForEach(group.entries) { entry in
                                    HistorySetRow(
                                        entry: entry,
                                        weightUnit: weightUnit,
                                        distanceUnit: distanceUnit,
                                        showsNotes: true,
                                        showsExerciseName: true
                                    )
                                    .opacity(deletingEntryIDs.contains(entry.id) ? 0.5 : 1)
                                    .swipeActions(edge: .leading, allowsFullSwipe: true) {
                                        Button {
                                            editingEntry = entry
                                        } label: {
                                            Label("Edit", systemImage: Icons.edit)
                                                .labelStyle(.iconOnly)
                                        }
                                        .tint(Color(.systemGray2))
                                    }
                                    .swipeActions(edge: .trailing, allowsFullSwipe: true) {
                                        Button(role: .destructive) {
                                            entryPendingDelete = entry
                                            showingEntryDeleteConfirm = true
                                        } label: {
                                            Label("Delete", systemImage: Icons.trash)
                                                .labelStyle(.iconOnly)
                                        }
                                        // Explicit red: the group's
                                        // accent tint would otherwise
                                        // bleed into the destructive
                                        // action and render it orange.
                                        .tint(DSColors.destructive)
                                    }
                                }
                            } label: {
                                Text("\(group.name) · \(group.entries.count)")
                                    .font(.subheadline.weight(.semibold))
                                    .foregroundStyle(DSColors.text)
                            }
                            .tint(DSColors.accent)
                        }
                    }
                }
            }

            if let error = store.errorMessage {
                Section {
                    Text(error)
                        .font(.footnote)
                        .foregroundStyle(DSColors.destructive)
                }
            }

            // Full-width action buttons in the DesignSystem
            // primary/secondary idiom: Duplicate is the safe,
            // reversible action (secondary chrome), Delete is
            // filled destructive. Both live in a single row so
            // no list separator or inter-row padding sits
            // between them — just a tight stack spacing.
            Section {
                VStack(spacing: DSSpacing.xs) {
                    Button {
                        showingDuplicate = true
                    } label: {
                        Text("Duplicate workout")
                    }
                    .buttonStyle(.dsSecondary)

                    Button(role: .destructive) {
                        showingDelete = true
                    } label: {
                        Text("Delete workout")
                    }
                    .font(.headline)
                    .foregroundStyle(.white)
                    .frame(maxWidth: .infinity)
                    .frame(height: 48)
                    .background(DSColors.destructive)
                    .clipShape(RoundedRectangle(cornerRadius: DSSpacing.cornerRadius, style: .continuous))
                }
                .listRowSeparator(.hidden)
            }
        }
        .listStyle(.automatic)
    }

    /// Loads the workout's logged sets for the history section.
    /// Best-effort: a failed refresh keeps the previous list
    /// rather than failing the whole screen.
    private func loadEntries() async {
        if let entries = try? await env.api.listWorkoutExerciseEntries(workoutID: workoutID) {
            loggedEntries = entries
        }
        entriesLoaded = true
    }

    /// Deletes a history entry via the API, removing it from the
    /// local list on success. Pessimistic — the row leaves only
    /// on a confirmed delete, so the section can never desync.
    private func deleteEntry(_ entry: ExerciseEntryDTO) async {
        entriesError = nil
        deletingEntryIDs.insert(entry.id)
        defer { deletingEntryIDs.remove(entry.id) }
        do {
            try await env.api.deleteExerciseEntry(id: entry.id)
            loggedEntries.removeAll { $0.id == entry.id }
        } catch let error as APIError {
            entriesError = error.errorDescription
        } catch {
            entriesError = "Could not delete the set."
        }
    }

    /// Two-way binding into `expandedHistoryGroups` for one
    /// history group. Name-keyed (not index-keyed): indices shift
    /// when a delete empties a group, which would make expansion
    /// follow the wrong group.
    private func historyGroupBinding(for name: String) -> Binding<Bool> {
        Binding(
            get: { expandedHistoryGroups.contains(name) },
            set: { expanded in
                if expanded {
                    expandedHistoryGroups.insert(name)
                } else {
                    expandedHistoryGroups.remove(name)
                }
            }
        )
    }

    /// Groups workout entries under their planned blocks in
    /// position order for the read-only history section. Matched
    /// on the stable catalogue `blockID` (same rule as the
    /// player's resume bucketing). Entries whose block is gone
    /// land in a trailing "Other" group. Buckets newest-first.
    /// Static so the math is directly unit-testable.
    static func groupedEntries(
        blocks: [WorkoutBlockDTO],
        entries: [ExerciseEntryDTO]
    ) -> [(name: String, entries: [ExerciseEntryDTO])] {
        var groups: [(name: String, entries: [ExerciseEntryDTO])] = []
        var seen = Set<String>()
        for block in blocks {
            let bucket = entries
                .filter { $0.blockID == block.blockID }
                .sorted { $0.createdAt > $1.createdAt }
            if !bucket.isEmpty {
                groups.append((block.blockName, bucket))
                seen.formUnion(bucket.map(\.id))
            }
        }
        let orphaned = entries
            .filter { !seen.contains($0.id) }
            .sorted { $0.createdAt > $1.createdAt }
        if !orphaned.isEmpty {
            groups.append(("Other", orphaned))
        }
        return groups
    }

    private var weightUnit: String {
        authStore.currentUser?.weightUnit ?? "kg"
    }

    private var distanceUnit: String {
        authStore.currentUser?.distanceUnit ?? "km"
    }

    /// Two-way binding for the status picker: writes go through the
    /// status-only endpoint so block check-offs survive. (The full
    /// `update` endpoint replaces every block with fresh pending
    /// rows — using it here wiped block progress on every status
    /// flip.)
    private func statusBinding(for workout: WorkoutDTO) -> Binding<WorkoutStatusDTO> {
        Binding(
            get: { workout.status },
            set: { newStatus in
                Task {
                    await store.setStatus(id: workout.id, status: newStatus)
                }
            }
        )
    }

    private func blockSubtitle(for block: WorkoutBlockDTO) -> String {
        let exercises = block.itemCount == 1 ? "1 exercise" : "\(block.itemCount) exercises"
        return "\(block.blockType.displayName) · \(exercises)"
    }

    /// Effective Apple Health activity type: the server key wins,
    /// unknown/missing keys read as the blanket default (never
    /// inference here — detail has no planned items to infer from).
    private func resolvedHealthActivityType(for workout: WorkoutDTO) -> HKWorkoutActivityType {
        WorkoutHealthActivityMapper.activityType(forKey: workout.healthActivityType)
            ?? .traditionalStrengthTraining
    }



    private func statusIcon(for status: WorkoutBlockStatusDTO) -> String {
        switch status {
        case .pending: return "circle"
        case .done: return "checkmark.circle"
        case .skipped: return "forward"
        }
    }

}

#Preview {
    NavigationStack {
        WorkoutDetailView(
            store: WorkoutStore(api: APIClient(
                baseURL: URL(string: "http://localhost:8080/api/v1")!,
                tokenProvider: { nil }
            )),
            blockStore: BlockStore(api: APIClient(
                baseURL: URL(string: "http://localhost:8080/api/v1")!,
                tokenProvider: { nil }
            )),
            workoutID: "preview"
        )
    }
    .environmentObject(AppEnvironment.live(baseURL: URL(string: "http://localhost:8080/api/v1")!))
    .environmentObject(AuthStore(api: APIClient(
        baseURL: URL(string: "http://localhost:8080/api/v1")!,
        tokenProvider: { nil }
    )))
}
