// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_reports.sql

package db

import (
	"context"
	"time"
)

const createAIReport = `-- name: CreateAIReport :one
INSERT INTO ai_reports (id, user_id, type, period_start, period_end, prompt_version, model, payload_json, tokens_in, tokens_out)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, type, period_start, period_end, prompt_version, model, payload_json, tokens_in, tokens_out, read_at, dismissed_at, created_at
`

type CreateAIReportParams struct {
	ID            string
	UserID        string
	Type          string
	PeriodStart   time.Time
	PeriodEnd     time.Time
	PromptVersion string
	Model         string
	PayloadJson   string
	TokensIn      int64
	TokensOut     int64
}

// Insert a Coach report. The caller enforces idempotency on
// (user_id, type, period_start): re-runs for the same week
// read the existing row via GetAIReport instead of inserting.
func (q *Queries) CreateAIReport(ctx context.Context, arg CreateAIReportParams) (AiReport, error) {
	row := q.db.QueryRowContext(ctx, createAIReport,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.PromptVersion,
		arg.Model,
		arg.PayloadJson,
		arg.TokensIn,
		arg.TokensOut,
	)
	var i AiReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PromptVersion,
		&i.Model,
		&i.PayloadJson,
		&i.TokensIn,
		&i.TokensOut,
		&i.ReadAt,
		&i.DismissedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAIReport = `-- name: GetAIReport :one
SELECT id, user_id, type, period_start, period_end, prompt_version, model, payload_json, tokens_in, tokens_out, read_at, dismissed_at, created_at FROM ai_reports
WHERE user_id = ? AND type = ? AND period_start = ?
`

type GetAIReportParams struct {
	UserID      string
	Type        string
	PeriodStart time.Time
}

// Fetch a single report for idempotency checks ((user_id, type,
// period_start) unique key) before deciding to call the LLM.
func (q *Queries) GetAIReport(ctx context.Context, arg GetAIReportParams) (AiReport, error) {
	row := q.db.QueryRowContext(ctx, getAIReport, arg.UserID, arg.Type, arg.PeriodStart)
	var i AiReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PromptVersion,
		&i.Model,
		&i.PayloadJson,
		&i.TokensIn,
		&i.TokensOut,
		&i.ReadAt,
		&i.DismissedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAIReportByID = `-- name: GetAIReportByID :one
SELECT id, user_id, type, period_start, period_end, prompt_version, model, payload_json, tokens_in, tokens_out, read_at, dismissed_at, created_at FROM ai_reports
WHERE id = ? AND user_id = ?
`

type GetAIReportByIDParams struct {
	ID     string
	UserID string
}

// Fetch a single report by id scoped to the user so a request
// cannot read or mutate another user's report.
func (q *Queries) GetAIReportByID(ctx context.Context, arg GetAIReportByIDParams) (AiReport, error) {
	row := q.db.QueryRowContext(ctx, getAIReportByID, arg.ID, arg.UserID)
	var i AiReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PromptVersion,
		&i.Model,
		&i.PayloadJson,
		&i.TokensIn,
		&i.TokensOut,
		&i.ReadAt,
		&i.DismissedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAIReport = `-- name: GetLatestAIReport :one
SELECT id, user_id, type, period_start, period_end, prompt_version, model, payload_json, tokens_in, tokens_out, read_at, dismissed_at, created_at FROM ai_reports
WHERE user_id = ? AND type = ?
ORDER BY period_start DESC
LIMIT 1
`

type GetLatestAIReportParams struct {
	UserID string
	Type   string
}

// The iOS Coach screen's primary read: newest report of a type.
func (q *Queries) GetLatestAIReport(ctx context.Context, arg GetLatestAIReportParams) (AiReport, error) {
	row := q.db.QueryRowContext(ctx, getLatestAIReport, arg.UserID, arg.Type)
	var i AiReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PromptVersion,
		&i.Model,
		&i.PayloadJson,
		&i.TokensIn,
		&i.TokensOut,
		&i.ReadAt,
		&i.DismissedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAIReports = `-- name: ListAIReports :many
SELECT id, user_id, type, period_start, period_end, prompt_version, model, payload_json, tokens_in, tokens_out, read_at, dismissed_at, created_at FROM ai_reports
WHERE user_id = ? AND type = ?
ORDER BY period_start DESC
LIMIT ?
`

type ListAIReportsParams struct {
	UserID string
	Type   string
	Limit  int64
}

// Report history for the iOS Coach screen, newest first.
func (q *Queries) ListAIReports(ctx context.Context, arg ListAIReportsParams) ([]AiReport, error) {
	rows, err := q.db.QueryContext(ctx, listAIReports, arg.UserID, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiReport
	for rows.Next() {
		var i AiReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PromptVersion,
			&i.Model,
			&i.PayloadJson,
			&i.TokensIn,
			&i.TokensOut,
			&i.ReadAt,
			&i.DismissedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAIReportDismissed = `-- name: MarkAIReportDismissed :exec
UPDATE ai_reports
SET dismissed_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type MarkAIReportDismissedParams struct {
	ID     string
	UserID string
}

// Stamp dismissed_at. Idempotent: re-dismissals overwrite.
func (q *Queries) MarkAIReportDismissed(ctx context.Context, arg MarkAIReportDismissedParams) error {
	_, err := q.db.ExecContext(ctx, markAIReportDismissed, arg.ID, arg.UserID)
	return err
}

const markAIReportRead = `-- name: MarkAIReportRead :exec
UPDATE ai_reports
SET read_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type MarkAIReportReadParams struct {
	ID     string
	UserID string
}

// Stamp read_at. Idempotent: re-reads overwrite the timestamp.
func (q *Queries) MarkAIReportRead(ctx context.Context, arg MarkAIReportReadParams) error {
	_, err := q.db.ExecContext(ctx, markAIReportRead, arg.ID, arg.UserID)
	return err
}
