// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package db

import (
	"context"
	"time"
)

const createBlock = `-- name: CreateBlock :one

INSERT INTO blocks (id, user_id, name, description, block_type, rounds, rest_seconds, time_cap_seconds, interval_seconds, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, description, block_type, rounds, rest_seconds, time_cap_seconds, interval_seconds, created_at, updated_at
`

type CreateBlockParams struct {
	ID              string
	UserID          string
	Name            string
	Description     string
	BlockType       string
	Rounds          int64
	RestSeconds     int64
	TimeCapSeconds  int64
	IntervalSeconds int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Blocks are user-owned planned exercise groups. Every query is
// scoped to user_id (via the blocks row) so a request can never read
// or mutate another user's plan.
func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRowContext(ctx, createBlock,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.BlockType,
		arg.Rounds,
		arg.RestSeconds,
		arg.TimeCapSeconds,
		arg.IntervalSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.BlockType,
		&i.Rounds,
		&i.RestSeconds,
		&i.TimeCapSeconds,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBlockItem = `-- name: CreateBlockItem :one
INSERT INTO block_items (id, block_id, exercise_id, position, target_text, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, block_id, exercise_id, position, target_text, created_at
`

type CreateBlockItemParams struct {
	ID         string
	BlockID    string
	ExerciseID string
	Position   int64
	TargetText string
	CreatedAt  time.Time
}

func (q *Queries) CreateBlockItem(ctx context.Context, arg CreateBlockItemParams) (BlockItem, error) {
	row := q.db.QueryRowContext(ctx, createBlockItem,
		arg.ID,
		arg.BlockID,
		arg.ExerciseID,
		arg.Position,
		arg.TargetText,
		arg.CreatedAt,
	)
	var i BlockItem
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.ExerciseID,
		&i.Position,
		&i.TargetText,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks
WHERE id = ? AND user_id = ?
`

type DeleteBlockParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, arg.ID, arg.UserID)
	return err
}

const deleteBlockItems = `-- name: DeleteBlockItems :exec
DELETE FROM block_items
WHERE block_id = ?
`

// Full item replacement on update: delete-all then re-insert in a
// transaction (the repository owns the tx). Also keeps deletes
// correct on databases ignoring ON DELETE CASCADE.
func (q *Queries) DeleteBlockItems(ctx context.Context, blockID string) error {
	_, err := q.db.ExecContext(ctx, deleteBlockItems, blockID)
	return err
}

const getBlock = `-- name: GetBlock :one
SELECT id, user_id, name, description, block_type, rounds, rest_seconds, time_cap_seconds, interval_seconds, created_at, updated_at FROM blocks
WHERE id = ? AND user_id = ?
`

type GetBlockParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetBlock(ctx context.Context, arg GetBlockParams) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlock, arg.ID, arg.UserID)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.BlockType,
		&i.Rounds,
		&i.RestSeconds,
		&i.TimeCapSeconds,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlockItems = `-- name: ListBlockItems :many
SELECT id, block_id, exercise_id, position, target_text, created_at FROM block_items
WHERE block_id = ?
ORDER BY position ASC
`

func (q *Queries) ListBlockItems(ctx context.Context, blockID string) ([]BlockItem, error) {
	rows, err := q.db.QueryContext(ctx, listBlockItems, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockItem
	for rows.Next() {
		var i BlockItem
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.ExerciseID,
			&i.Position,
			&i.TargetText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockItemsWithExercise = `-- name: ListBlockItemsWithExercise :many
SELECT i.id, i.block_id, i.exercise_id, i.position, i.target_text, i.created_at,
       e.name AS exercise_name, e.type AS exercise_type
FROM block_items i
JOIN exercises e ON e.id = i.exercise_id
WHERE i.block_id = ?
ORDER BY i.position ASC
`

type ListBlockItemsWithExerciseRow struct {
	ID           string
	BlockID      string
	ExerciseID   string
	Position     int64
	TargetText   string
	CreatedAt    time.Time
	ExerciseName string
	ExerciseType string
}

// Detail view resolves each planned item to its exercise name/type
// in one query. Ownership is gated by the caller's prior GetBlock
// (scoped to user_id); this query only orders the items.
func (q *Queries) ListBlockItemsWithExercise(ctx context.Context, blockID string) ([]ListBlockItemsWithExerciseRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlockItemsWithExercise, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockItemsWithExerciseRow
	for rows.Next() {
		var i ListBlockItemsWithExerciseRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.ExerciseID,
			&i.Position,
			&i.TargetText,
			&i.CreatedAt,
			&i.ExerciseName,
			&i.ExerciseType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, user_id, name, description, block_type, rounds, rest_seconds, time_cap_seconds, interval_seconds, created_at, updated_at FROM blocks
WHERE user_id = ?
ORDER BY created_at DESC, rowid DESC
`

// Newest first; rowid breaks created_at ties (same convention as
// exercise_entries ordering).
func (q *Queries) ListBlocks(ctx context.Context, userID string) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.BlockType,
			&i.Rounds,
			&i.RestSeconds,
			&i.TimeCapSeconds,
			&i.IntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksWithItemCount = `-- name: ListBlocksWithItemCount :many
SELECT b.id, b.user_id, b.name, b.description, b.block_type, b.rounds, b.rest_seconds, b.time_cap_seconds, b.interval_seconds, b.created_at, b.updated_at, COUNT(i.id) AS item_count FROM blocks b
LEFT JOIN block_items i ON i.block_id = b.id
WHERE b.user_id = ?
GROUP BY b.id
ORDER BY b.created_at DESC, b.rowid DESC
`

type ListBlocksWithItemCountRow struct {
	ID              string
	UserID          string
	Name            string
	Description     string
	BlockType       string
	Rounds          int64
	RestSeconds     int64
	TimeCapSeconds  int64
	IntervalSeconds int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ItemCount       int64
}

// List view needs per-block item counts without N+1 queries.
func (q *Queries) ListBlocksWithItemCount(ctx context.Context, userID string) ([]ListBlocksWithItemCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlocksWithItemCount, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlocksWithItemCountRow
	for rows.Next() {
		var i ListBlocksWithItemCountRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.BlockType,
			&i.Rounds,
			&i.RestSeconds,
			&i.TimeCapSeconds,
			&i.IntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlock = `-- name: UpdateBlock :exec
UPDATE blocks
SET name = ?,
    description = ?,
    block_type = ?,
    rounds = ?,
    rest_seconds = ?,
    time_cap_seconds = ?,
    interval_seconds = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateBlockParams struct {
	Name            string
	Description     string
	BlockType       string
	Rounds          int64
	RestSeconds     int64
	TimeCapSeconds  int64
	IntervalSeconds int64
	ID              string
	UserID          string
}

// Overwrites the editable block fields and bumps updated_at.
// Items are replaced separately via DeleteBlockItems + CreateBlockItem.
func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) error {
	_, err := q.db.ExecContext(ctx, updateBlock,
		arg.Name,
		arg.Description,
		arg.BlockType,
		arg.Rounds,
		arg.RestSeconds,
		arg.TimeCapSeconds,
		arg.IntervalSeconds,
		arg.ID,
		arg.UserID,
	)
	return err
}
