// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_snapshots.sql

package db

import (
	"context"
	"database/sql"
)

const getHealthSnapshotByDate = `-- name: GetHealthSnapshotByDate :one
SELECT id, user_id, snapshot_date, tz, steps, distance_meters, active_energy_kcal, basal_energy_kcal, exercise_minutes, sleep_seconds, weight, weight_measured_at, bmi, bmi_measured_at, body_fat_percentage, body_fat_measured_at, lean_body_mass, lean_mass_measured_at, heart_rate, heart_rate_measured_at, resting_heart_rate, resting_hr_measured_at, walking_heart_rate_avg, walking_hr_measured_at, hrv_ms, hrv_measured_at, cardio_recovery_bpm, cardio_recovery_measured_at, vo2_max, vo2_measured_at, created_at, updated_at FROM health_snapshots
WHERE user_id = ? AND snapshot_date = ?
`

type GetHealthSnapshotByDateParams struct {
	UserID       string
	SnapshotDate string
}

func (q *Queries) GetHealthSnapshotByDate(ctx context.Context, arg GetHealthSnapshotByDateParams) (HealthSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getHealthSnapshotByDate, arg.UserID, arg.SnapshotDate)
	var i HealthSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.Tz,
		&i.Steps,
		&i.DistanceMeters,
		&i.ActiveEnergyKcal,
		&i.BasalEnergyKcal,
		&i.ExerciseMinutes,
		&i.SleepSeconds,
		&i.Weight,
		&i.WeightMeasuredAt,
		&i.Bmi,
		&i.BmiMeasuredAt,
		&i.BodyFatPercentage,
		&i.BodyFatMeasuredAt,
		&i.LeanBodyMass,
		&i.LeanMassMeasuredAt,
		&i.HeartRate,
		&i.HeartRateMeasuredAt,
		&i.RestingHeartRate,
		&i.RestingHrMeasuredAt,
		&i.WalkingHeartRateAvg,
		&i.WalkingHrMeasuredAt,
		&i.HrvMs,
		&i.HrvMeasuredAt,
		&i.CardioRecoveryBpm,
		&i.CardioRecoveryMeasuredAt,
		&i.Vo2Max,
		&i.Vo2MeasuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHealthSnapshotsRange = `-- name: ListHealthSnapshotsRange :many
SELECT id, user_id, snapshot_date, tz, steps, distance_meters, active_energy_kcal, basal_energy_kcal, exercise_minutes, sleep_seconds, weight, weight_measured_at, bmi, bmi_measured_at, body_fat_percentage, body_fat_measured_at, lean_body_mass, lean_mass_measured_at, heart_rate, heart_rate_measured_at, resting_heart_rate, resting_hr_measured_at, walking_heart_rate_avg, walking_hr_measured_at, hrv_ms, hrv_measured_at, cardio_recovery_bpm, cardio_recovery_measured_at, vo2_max, vo2_measured_at, created_at, updated_at FROM health_snapshots
WHERE user_id = ? AND snapshot_date >= ? AND snapshot_date <= ?
ORDER BY snapshot_date DESC
`

type ListHealthSnapshotsRangeParams struct {
	UserID         string
	SnapshotDate   string
	SnapshotDate_2 string
}

func (q *Queries) ListHealthSnapshotsRange(ctx context.Context, arg ListHealthSnapshotsRangeParams) ([]HealthSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listHealthSnapshotsRange, arg.UserID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthSnapshot
	for rows.Next() {
		var i HealthSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SnapshotDate,
			&i.Tz,
			&i.Steps,
			&i.DistanceMeters,
			&i.ActiveEnergyKcal,
			&i.BasalEnergyKcal,
			&i.ExerciseMinutes,
			&i.SleepSeconds,
			&i.Weight,
			&i.WeightMeasuredAt,
			&i.Bmi,
			&i.BmiMeasuredAt,
			&i.BodyFatPercentage,
			&i.BodyFatMeasuredAt,
			&i.LeanBodyMass,
			&i.LeanMassMeasuredAt,
			&i.HeartRate,
			&i.HeartRateMeasuredAt,
			&i.RestingHeartRate,
			&i.RestingHrMeasuredAt,
			&i.WalkingHeartRateAvg,
			&i.WalkingHrMeasuredAt,
			&i.HrvMs,
			&i.HrvMeasuredAt,
			&i.CardioRecoveryBpm,
			&i.CardioRecoveryMeasuredAt,
			&i.Vo2Max,
			&i.Vo2MeasuredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHealthSnapshot = `-- name: UpsertHealthSnapshot :one
INSERT INTO health_snapshots (
    id, user_id, snapshot_date, tz,
    steps, distance_meters, active_energy_kcal, basal_energy_kcal,
    exercise_minutes, sleep_seconds,
    weight, weight_measured_at,
    bmi, bmi_measured_at,
    body_fat_percentage, body_fat_measured_at,
    lean_body_mass, lean_mass_measured_at,
    heart_rate, heart_rate_measured_at,
    resting_heart_rate, resting_hr_measured_at,
    walking_heart_rate_avg, walking_hr_measured_at,
    hrv_ms, hrv_measured_at,
    cardio_recovery_bpm, cardio_recovery_measured_at,
    vo2_max, vo2_measured_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?
)
ON CONFLICT(user_id, snapshot_date) DO UPDATE SET
    tz = excluded.tz,
    steps = excluded.steps,
    distance_meters = excluded.distance_meters,
    active_energy_kcal = excluded.active_energy_kcal,
    basal_energy_kcal = excluded.basal_energy_kcal,
    exercise_minutes = excluded.exercise_minutes,
    sleep_seconds = excluded.sleep_seconds,
    weight = excluded.weight,
    weight_measured_at = excluded.weight_measured_at,
    bmi = excluded.bmi,
    bmi_measured_at = excluded.bmi_measured_at,
    body_fat_percentage = excluded.body_fat_percentage,
    body_fat_measured_at = excluded.body_fat_measured_at,
    lean_body_mass = excluded.lean_body_mass,
    lean_mass_measured_at = excluded.lean_mass_measured_at,
    heart_rate = excluded.heart_rate,
    heart_rate_measured_at = excluded.heart_rate_measured_at,
    resting_heart_rate = excluded.resting_heart_rate,
    resting_hr_measured_at = excluded.resting_hr_measured_at,
    walking_heart_rate_avg = excluded.walking_heart_rate_avg,
    walking_hr_measured_at = excluded.walking_hr_measured_at,
    hrv_ms = excluded.hrv_ms,
    hrv_measured_at = excluded.hrv_measured_at,
    cardio_recovery_bpm = excluded.cardio_recovery_bpm,
    cardio_recovery_measured_at = excluded.cardio_recovery_measured_at,
    vo2_max = excluded.vo2_max,
    vo2_measured_at = excluded.vo2_measured_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, snapshot_date, tz, steps, distance_meters, active_energy_kcal, basal_energy_kcal, exercise_minutes, sleep_seconds, weight, weight_measured_at, bmi, bmi_measured_at, body_fat_percentage, body_fat_measured_at, lean_body_mass, lean_mass_measured_at, heart_rate, heart_rate_measured_at, resting_heart_rate, resting_hr_measured_at, walking_heart_rate_avg, walking_hr_measured_at, hrv_ms, hrv_measured_at, cardio_recovery_bpm, cardio_recovery_measured_at, vo2_max, vo2_measured_at, created_at, updated_at
`

type UpsertHealthSnapshotParams struct {
	ID                       string
	UserID                   string
	SnapshotDate             string
	Tz                       string
	Steps                    int64
	DistanceMeters           float64
	ActiveEnergyKcal         float64
	BasalEnergyKcal          float64
	ExerciseMinutes          float64
	SleepSeconds             float64
	Weight                   float64
	WeightMeasuredAt         sql.NullTime
	Bmi                      float64
	BmiMeasuredAt            sql.NullTime
	BodyFatPercentage        float64
	BodyFatMeasuredAt        sql.NullTime
	LeanBodyMass             float64
	LeanMassMeasuredAt       sql.NullTime
	HeartRate                float64
	HeartRateMeasuredAt      sql.NullTime
	RestingHeartRate         float64
	RestingHrMeasuredAt      sql.NullTime
	WalkingHeartRateAvg      float64
	WalkingHrMeasuredAt      sql.NullTime
	HrvMs                    float64
	HrvMeasuredAt            sql.NullTime
	CardioRecoveryBpm        float64
	CardioRecoveryMeasuredAt sql.NullTime
	Vo2Max                   float64
	Vo2MeasuredAt            sql.NullTime
}

func (q *Queries) UpsertHealthSnapshot(ctx context.Context, arg UpsertHealthSnapshotParams) (HealthSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertHealthSnapshot,
		arg.ID,
		arg.UserID,
		arg.SnapshotDate,
		arg.Tz,
		arg.Steps,
		arg.DistanceMeters,
		arg.ActiveEnergyKcal,
		arg.BasalEnergyKcal,
		arg.ExerciseMinutes,
		arg.SleepSeconds,
		arg.Weight,
		arg.WeightMeasuredAt,
		arg.Bmi,
		arg.BmiMeasuredAt,
		arg.BodyFatPercentage,
		arg.BodyFatMeasuredAt,
		arg.LeanBodyMass,
		arg.LeanMassMeasuredAt,
		arg.HeartRate,
		arg.HeartRateMeasuredAt,
		arg.RestingHeartRate,
		arg.RestingHrMeasuredAt,
		arg.WalkingHeartRateAvg,
		arg.WalkingHrMeasuredAt,
		arg.HrvMs,
		arg.HrvMeasuredAt,
		arg.CardioRecoveryBpm,
		arg.CardioRecoveryMeasuredAt,
		arg.Vo2Max,
		arg.Vo2MeasuredAt,
	)
	var i HealthSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.Tz,
		&i.Steps,
		&i.DistanceMeters,
		&i.ActiveEnergyKcal,
		&i.BasalEnergyKcal,
		&i.ExerciseMinutes,
		&i.SleepSeconds,
		&i.Weight,
		&i.WeightMeasuredAt,
		&i.Bmi,
		&i.BmiMeasuredAt,
		&i.BodyFatPercentage,
		&i.BodyFatMeasuredAt,
		&i.LeanBodyMass,
		&i.LeanMassMeasuredAt,
		&i.HeartRate,
		&i.HeartRateMeasuredAt,
		&i.RestingHeartRate,
		&i.RestingHrMeasuredAt,
		&i.WalkingHeartRateAvg,
		&i.WalkingHrMeasuredAt,
		&i.HrvMs,
		&i.HrvMeasuredAt,
		&i.CardioRecoveryBpm,
		&i.CardioRecoveryMeasuredAt,
		&i.Vo2Max,
		&i.Vo2MeasuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
