// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AiReport struct {
	ID            string
	UserID        string
	Type          string
	PeriodStart   time.Time
	PeriodEnd     time.Time
	PromptVersion string
	Model         string
	PayloadJson   string
	TokensIn      int64
	TokensOut     int64
	DismissedAt   sql.NullTime
	CreatedAt     time.Time
}

type AuthToken struct {
	ID        string
	UserID    string
	Purpose   string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Block struct {
	ID              string
	UserID          string
	Name            string
	Description     string
	BlockType       string
	Rounds          int64
	RestSeconds     int64
	TimeCapSeconds  int64
	IntervalSeconds int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type BlockItem struct {
	ID         string
	BlockID    string
	ExerciseID string
	Position   int64
	TargetText string
	CreatedAt  time.Time
}

type Exercise struct {
	ID             string
	Name           string
	Aliases        string
	Description    sql.NullString
	VideoUrl       sql.NullString
	ImgUrl         sql.NullString
	ImgUrlOriginal sql.NullString
	Type           string
}

type ExerciseEntry struct {
	ID              string
	ExerciseID      string
	UserID          sql.NullString
	Reps            int64
	Weight          float64
	Notes           sql.NullString
	RestTime        int64
	DurationSeconds int64
	DistanceMeters  float64
	AvgHeartRate    int64
	CaloriesBurned  float64
	CreatedAt       sql.NullTime
}

type Feedback struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsClosed  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Goal struct {
	ID          string
	UserID      string
	Title       string
	Description sql.NullString
	StartDate   sql.NullTime
	TargetDate  sql.NullTime
	EndDate     sql.NullTime
	CompletedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type HealthSnapshot struct {
	ID                       string
	UserID                   string
	SnapshotDate             string
	Tz                       string
	Steps                    int64
	DistanceMeters           float64
	ActiveEnergyKcal         float64
	BasalEnergyKcal          float64
	ExerciseMinutes          float64
	SleepSeconds             float64
	Weight                   float64
	WeightMeasuredAt         sql.NullTime
	Bmi                      float64
	BmiMeasuredAt            sql.NullTime
	BodyFatPercentage        float64
	BodyFatMeasuredAt        sql.NullTime
	LeanBodyMass             float64
	LeanMassMeasuredAt       sql.NullTime
	HeartRate                float64
	HeartRateMeasuredAt      sql.NullTime
	RestingHeartRate         float64
	RestingHrMeasuredAt      sql.NullTime
	WalkingHeartRateAvg      float64
	WalkingHrMeasuredAt      sql.NullTime
	HrvMs                    float64
	HrvMeasuredAt            sql.NullTime
	CardioRecoveryBpm        float64
	CardioRecoveryMeasuredAt sql.NullTime
	Vo2Max                   float64
	Vo2MeasuredAt            sql.NullTime
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type PushSubscription struct {
	ID         string
	UserID     string
	Endpoint   string
	P256dh     string
	Auth       string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type User struct {
	ID                   string
	Name                 string
	Email                string
	PasswordHash         string
	IsAdmin              int64
	TargetWeight         sql.NullFloat64
	WeightUnit           string
	DistanceUnit         string
	ReminderEnabled      int64
	ReminderFrequency    string
	ReminderDayOfWeek    sql.NullInt64
	ReminderTime         string
	ReminderEmailEnabled int64
	ReminderPushEnabled  int64
	ReminderNextFireAt   sql.NullTime
	ReminderLastFiredAt  sql.NullTime
	AiOptIn              int64
	AiGoalText           string
	HeightCm             sql.NullFloat64
	Gender               string
	DateOfBirth          sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type WeightEntry struct {
	ID            string
	UserID        string
	Weight        float64
	Notes         sql.NullString
	FrontPhotoKey sql.NullString
	SidePhotoKey  sql.NullString
	BackPhotoKey  sql.NullString
	CreatedAt     time.Time
}

type Workout struct {
	ID          string
	UserID      string
	Title       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WorkoutAssignment struct {
	ID            string
	WorkoutID     string
	UserID        string
	ScheduledDate string
	CreatedAt     time.Time
}

type WorkoutBlock struct {
	ID        string
	WorkoutID string
	BlockID   string
	Position  int64
	CreatedAt time.Time
}
