// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Atomically claim a token: marks used_at and returns the row only
	// when the token exists for the given purpose, has not been used,
	// and has not expired. The single-statement UPDATE...RETURNING is
	// the concurrency primitive that prevents double-use across tabs,
	// devices, or racing requests.
	//
	// `expires_at` comparison uses the literal `datetime('now')` rather
	// than a parameter so the database clock (not the application clock)
	// decides what "expired" means. SQLite's datetime('now') returns
	// UTC, matching the value written by the application.
	ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (AuthToken, error)
	Create(ctx context.Context, arg CreateParams) (string, error)
	// Insert a Coach report. The caller enforces idempotency on
	// (user_id, type, period_start): re-runs for the same week
	// read the existing row via GetAIReport instead of inserting.
	CreateAIReport(ctx context.Context, arg CreateAIReportParams) (AiReport, error)
	// Insert a new auth token row. The caller is responsible for hashing
	// the raw token with sha256 before storing. The raw token only ever
	// lives in the email link; the database never sees it.
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	// Blocks are user-owned planned exercise groups. Every query is
	// scoped to user_id (via the blocks row) so a request can never read
	// or mutate another user's plan.
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
	CreateBlockItem(ctx context.Context, arg CreateBlockItemParams) (BlockItem, error)
	CreateExerciseEntry(ctx context.Context, arg CreateExerciseEntryParams) (string, error)
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	CreateWeightEntry(ctx context.Context, arg CreateWeightEntryParams) (WeightEntry, error)
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	// Full item replacement on update: delete-all then re-insert in a
	// transaction (the repository owns the tx). Also keeps deletes
	// correct on databases ignoring ON DELETE CASCADE.
	DeleteBlockItems(ctx context.Context, blockID string) error
	DeleteExerciseEntry(ctx context.Context, arg DeleteExerciseEntryParams) error
	DeleteGoal(ctx context.Context, arg DeleteGoalParams) error
	DeleteWeightEntry(ctx context.Context, arg DeleteWeightEntryParams) error
	// Fetch a single report for idempotency checks ((user_id, type,
	// period_start) unique key) before deciding to call the LLM.
	GetAIReport(ctx context.Context, arg GetAIReportParams) (AiReport, error)
	// Fetch a single report by id scoped to the user so a request
	// cannot read or mutate another user's report.
	GetAIReportByID(ctx context.Context, arg GetAIReportByIDParams) (AiReport, error)
	GetAll(ctx context.Context) ([]GetAllRow, error)
	GetAllClosed(ctx context.Context) ([]GetAllClosedRow, error)
	GetAllOpen(ctx context.Context) ([]GetAllOpenRow, error)
	// Fastest pace in seconds per kilometre across a user's cardio exercise entries
	// (duration divided by distance). Entries without distance are excluded;
	// returns 0 when no qualifying exercise entries exist.
	GetBestPaceByExercise(ctx context.Context, arg GetBestPaceByExerciseParams) (float64, error)
	GetBlock(ctx context.Context, arg GetBlockParams) (Block, error)
	GetByID(ctx context.Context, id string) (Exercise, error)
	GetByName(ctx context.Context, name string) (Exercise, error)
	GetExerciseEntriesByDateRange(ctx context.Context, arg GetExerciseEntriesByDateRangeParams) ([]GetExerciseEntriesByDateRangeRow, error)
	GetExerciseEntriesByExercisePaginated(ctx context.Context, arg GetExerciseEntriesByExercisePaginatedParams) ([]GetExerciseEntriesByExercisePaginatedRow, error)
	GetExerciseEntry(ctx context.Context, arg GetExerciseEntryParams) (GetExerciseEntryRow, error)
	GetFeedbackByID(ctx context.Context, id string) (GetFeedbackByIDRow, error)
	GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error)
	GetHealthSnapshotByDate(ctx context.Context, arg GetHealthSnapshotByDateParams) (HealthSnapshot, error)
	GetLastSetByExercise(ctx context.Context, arg GetLastSetByExerciseParams) (GetLastSetByExerciseRow, error)
	// The iOS Coach screen's primary read: newest report of a type.
	GetLatestAIReport(ctx context.Context, arg GetLatestAIReportParams) (AiReport, error)
	// Longest distance in metres logged for an exercise. Returns 0 when no exercise entries exist.
	GetLongestDistanceByExercise(ctx context.Context, arg GetLongestDistanceByExerciseParams) (float64, error)
	// Best single-set volume (reps * weight) logged for a strength exercise.
	// Returns 0 when no exercise entries exist.
	GetMaxSetVolumeByExercise(ctx context.Context, arg GetMaxSetVolumeByExerciseParams) (float64, error)
	// Heaviest weight logged for a strength exercise. Returns 0 when no exercise entries exist.
	GetMaxWeightByExercise(ctx context.Context, arg GetMaxWeightByExerciseParams) (float64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWeightEntriesByIDs(ctx context.Context, arg GetWeightEntriesByIDsParams) ([]WeightEntry, error)
	GetWeightEntry(ctx context.Context, arg GetWeightEntryParams) (WeightEntry, error)
	List(ctx context.Context) ([]Exercise, error)
	// Every user with ai_opt_in = 1. The weekly Coach cron iterates
	// this list; per-user report generation is idempotent on
	// (user_id, type, period_start) so overlapping ticks are safe.
	ListAIOptedInUsers(ctx context.Context) ([]User, error)
	// Report history for the iOS Coach screen, newest first.
	ListAIReports(ctx context.Context, arg ListAIReportsParams) ([]AiReport, error)
	// Active goals: completed_at IS NULL. Order by target_date asc with nulls
	// last, then by created_at asc as a stable tiebreaker. The CASE expression
	// emulates NULLS LAST for SQLite versions that don't support it natively.
	ListActiveGoals(ctx context.Context, userID string) ([]Goal, error)
	ListBlockItems(ctx context.Context, blockID string) ([]BlockItem, error)
	// Detail view resolves each planned item to its exercise name/type
	// in one query. Ownership is gated by the caller's prior GetBlock
	// (scoped to user_id); this query only orders the items.
	ListBlockItemsWithExercise(ctx context.Context, blockID string) ([]ListBlockItemsWithExerciseRow, error)
	// Newest first; rowid breaks created_at ties (same convention as
	// exercise_entries ordering).
	ListBlocks(ctx context.Context, userID string) ([]Block, error)
	// List view needs per-block item counts without N+1 queries.
	ListBlocksWithItemCount(ctx context.Context, userID string) ([]ListBlocksWithItemCountRow, error)
	// Completed goals: completed_at IS NOT NULL. Most recently completed first.
	ListCompletedGoals(ctx context.Context, userID string) ([]Goal, error)
	ListExerciseEntries(ctx context.Context, userID sql.NullString) ([]ListExerciseEntriesRow, error)
	ListExerciseEntriesLast7Days(ctx context.Context, userID sql.NullString) ([]ListExerciseEntriesLast7DaysRow, error)
	ListExerciseEntriesWithLimit(ctx context.Context, arg ListExerciseEntriesWithLimitParams) ([]ListExerciseEntriesWithLimitRow, error)
	ListHealthSnapshotsRange(ctx context.Context, arg ListHealthSnapshotsRangeParams) ([]HealthSnapshot, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Returns every enabled user whose next_fire_at is at or before the
	// supplied reference time. The hourly tick calls this once per hour;
	// the indexed next_fire_at column keeps the scan small even when the
	// users table grows. We pull back the full row so the orchestrator can
	// build its email payload without an extra round-trip.
	ListUsersDueForReminder(ctx context.Context, reminderNextFireAt sql.NullTime) ([]User, error)
	ListWeightEntries(ctx context.Context, userID string) ([]WeightEntry, error)
	// Stamp dismissed_at. Idempotent: re-dismissals overwrite.
	MarkAIReportDismissed(ctx context.Context, arg MarkAIReportDismissedParams) error
	// Atomically set completed_at and bump updated_at. Scoped to user_id so
	// the request cannot mark another user's goal complete.
	MarkGoalComplete(ctx context.Context, arg MarkGoalCompleteParams) error
	// Atomically set last_fired_at = now and advance next_fire_at to the
	// caller's computed next occurrence. Scoped to id so a misbehaving
	// caller cannot advance another user's row. updated_at is bumped so
	// the row's edit history stays accurate (useful for future "when was
	// this user last updated" UI).
	MarkUserReminderFired(ctx context.Context, arg MarkUserReminderFiredParams) error
	// Clear dismissed_at, returning the report to the card list.
	// Idempotent: reopening a non-dismissed row is a no-op that
	// still matches (so the route can call it without checking).
	ReopenAIReport(ctx context.Context, arg ReopenAIReportParams) error
	// Atomically clear completed_at and bump updated_at. No-op if the goal
	// is already active (completed_at is already NULL), so the route can
	// call it without first checking the current state.
	ReopenGoal(ctx context.Context, arg ReopenGoalParams) error
	// Grant or revoke a user's admin status. Scoped to id; the RETURNING
	// clause turns "no such user" into sql.ErrNoRows so the repository
	// can surface a clean not-found error instead of silently no-oping.
	// Separate from UpdateUser for the same reason as UpdateUserPassword:
	// a narrow, single-purpose query prevents the admin form from
	// clobbering any other columns.
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (string, error)
	Update(ctx context.Context, arg UpdateParams) (Exercise, error)
	// Overwrites the editable block fields and bumps updated_at.
	// Items are replaced separately via DeleteBlockItems + CreateBlockItem.
	UpdateBlock(ctx context.Context, arg UpdateBlockParams) error
	UpdateExerciseEntry(ctx context.Context, arg UpdateExerciseEntryParams) error
	UpdateExerciseEntryWithDate(ctx context.Context, arg UpdateExerciseEntryWithDateParams) error
	// Update the editable fields. completed_at is managed by MarkGoalComplete
	// and ReopenGoal (single-purpose methods that don't touch the rest of the
	// row), so the edit form cannot accidentally clear or set the completed
	// state. updated_at is bumped automatically.
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Feedback, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	// Narrow write for the Coach opt-in toggle + free-text aim, kept
	// separate from UpdateUser / UpdateUserReminder so no other form
	// can clobber AI consent state. ai_goal_text is capped at 1000
	// chars app-side; the query stores it verbatim.
	UpdateUserAIPreferences(ctx context.Context, arg UpdateUserAIPreferencesParams) error
	// Replace a user's password hash. Used by the password-reset flow
	// after a reset token has been successfully consumed. Separate from
	// UpdateUser so the profile-editing form cannot be tricked into
	// clearing the password by omitting fields.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Replace a user's reminder preferences and bump updated_at so the
	// row is re-evaluated by the periodic tick on the next run. The day
	// of week is nullable because off / daily frequencies don't need it;
	// every other parameter is required and is asserted by the controller
	// before the call. next_fire_at is recomputed by the caller and passed
	// in as a parameter; we do not derive it here so the same query works
	// for both "user changed preferences" and "tick just fired" callers.
	UpdateUserReminder(ctx context.Context, arg UpdateUserReminderParams) error
	UpdateWeightEntry(ctx context.Context, arg UpdateWeightEntryParams) error
	UpsertHealthSnapshot(ctx context.Context, arg UpsertHealthSnapshotParams) (HealthSnapshot, error)
}

var _ Querier = (*Queries)(nil)
