// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workouts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWorkout = `-- name: CreateWorkout :one

INSERT INTO workouts (id, user_id, source_workout_id, name, notes, status, scheduled_start, scheduled_end, completed_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, source_workout_id, name, notes, status, scheduled_start, scheduled_end, completed_at, created_at, updated_at
`

type CreateWorkoutParams struct {
	ID              string
	UserID          string
	SourceWorkoutID sql.NullString
	Name            string
	Notes           sql.NullString
	Status          string
	ScheduledStart  sql.NullTime
	ScheduledEnd    sql.NullTime
	CompletedAt     sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Workouts: dated containers scoped to the user.
func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.ID,
		arg.UserID,
		arg.SourceWorkoutID,
		arg.Name,
		arg.Notes,
		arg.Status,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceWorkoutID,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkoutBlock = `-- name: CreateWorkoutBlock :one
INSERT INTO workout_blocks (id, workout_id, type, position, rounds, rest_between_rounds_seconds, interval_seconds, time_cap_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workout_id, type, position, rounds, rest_between_rounds_seconds, interval_seconds, time_cap_seconds
`

type CreateWorkoutBlockParams struct {
	ID                       string
	WorkoutID                string
	Type                     string
	Position                 int64
	Rounds                   int64
	RestBetweenRoundsSeconds int64
	IntervalSeconds          int64
	TimeCapSeconds           int64
}

func (q *Queries) CreateWorkoutBlock(ctx context.Context, arg CreateWorkoutBlockParams) (WorkoutBlock, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutBlock,
		arg.ID,
		arg.WorkoutID,
		arg.Type,
		arg.Position,
		arg.Rounds,
		arg.RestBetweenRoundsSeconds,
		arg.IntervalSeconds,
		arg.TimeCapSeconds,
	)
	var i WorkoutBlock
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.Type,
		&i.Position,
		&i.Rounds,
		&i.RestBetweenRoundsSeconds,
		&i.IntervalSeconds,
		&i.TimeCapSeconds,
	)
	return i, err
}

const createWorkoutItem = `-- name: CreateWorkoutItem :one
INSERT INTO workout_items (id, block_id, exercise_id, position, target_sets, target_reps, target_weight, target_rest_seconds, target_duration_seconds, target_distance_meters, target_avg_heart_rate, target_calories)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, block_id, exercise_id, position, target_sets, target_reps, target_weight, target_rest_seconds, target_duration_seconds, target_distance_meters, target_avg_heart_rate, target_calories
`

type CreateWorkoutItemParams struct {
	ID                    string
	BlockID               string
	ExerciseID            string
	Position              int64
	TargetSets            int64
	TargetReps            int64
	TargetWeight          float64
	TargetRestSeconds     int64
	TargetDurationSeconds int64
	TargetDistanceMeters  float64
	TargetAvgHeartRate    int64
	TargetCalories        float64
}

func (q *Queries) CreateWorkoutItem(ctx context.Context, arg CreateWorkoutItemParams) (WorkoutItem, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutItem,
		arg.ID,
		arg.BlockID,
		arg.ExerciseID,
		arg.Position,
		arg.TargetSets,
		arg.TargetReps,
		arg.TargetWeight,
		arg.TargetRestSeconds,
		arg.TargetDurationSeconds,
		arg.TargetDistanceMeters,
		arg.TargetAvgHeartRate,
		arg.TargetCalories,
	)
	var i WorkoutItem
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.ExerciseID,
		&i.Position,
		&i.TargetSets,
		&i.TargetReps,
		&i.TargetWeight,
		&i.TargetRestSeconds,
		&i.TargetDurationSeconds,
		&i.TargetDistanceMeters,
		&i.TargetAvgHeartRate,
		&i.TargetCalories,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts
WHERE id = ? AND user_id = ?
`

type DeleteWorkoutParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkout, arg.ID, arg.UserID)
	return err
}

const deleteWorkoutBlocksByWorkout = `-- name: DeleteWorkoutBlocksByWorkout :exec
DELETE FROM workout_blocks
WHERE workout_id = ?
`

func (q *Queries) DeleteWorkoutBlocksByWorkout(ctx context.Context, workoutID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutBlocksByWorkout, workoutID)
	return err
}

const getWorkout = `-- name: GetWorkout :one
SELECT id, user_id, source_workout_id, name, notes, status, scheduled_start, scheduled_end, completed_at, created_at, updated_at FROM workouts
WHERE id = ? AND user_id = ?
`

type GetWorkoutParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetWorkout(ctx context.Context, arg GetWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkout, arg.ID, arg.UserID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceWorkoutID,
		&i.Name,
		&i.Notes,
		&i.Status,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutBlock = `-- name: GetWorkoutBlock :one
SELECT wb.id, wb.workout_id, wb.type, wb.position, wb.rounds, wb.rest_between_rounds_seconds, wb.interval_seconds, wb.time_cap_seconds FROM workout_blocks wb
JOIN workouts w ON wb.workout_id = w.id
WHERE wb.id = ? AND w.user_id = ?
`

type GetWorkoutBlockParams struct {
	ID     string
	UserID string
}

// Single workout block scoped to the user via its workout parentage.
func (q *Queries) GetWorkoutBlock(ctx context.Context, arg GetWorkoutBlockParams) (WorkoutBlock, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutBlock, arg.ID, arg.UserID)
	var i WorkoutBlock
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.Type,
		&i.Position,
		&i.Rounds,
		&i.RestBetweenRoundsSeconds,
		&i.IntervalSeconds,
		&i.TimeCapSeconds,
	)
	return i, err
}

const getWorkoutItem = `-- name: GetWorkoutItem :one
SELECT wi.id, wi.block_id, wi.exercise_id, wi.position, wi.target_sets, wi.target_reps, wi.target_weight, wi.target_rest_seconds, wi.target_duration_seconds, wi.target_distance_meters, wi.target_avg_heart_rate, wi.target_calories FROM workout_items wi
JOIN workout_blocks wb ON wi.block_id = wb.id
JOIN workouts w ON wb.workout_id = w.id
WHERE wi.id = ? AND w.user_id = ?
`

type GetWorkoutItemParams struct {
	ID     string
	UserID string
}

// Single workout item scoped to the user via its workout parentage.
// Used to validate the exercise-entry logging triple.
func (q *Queries) GetWorkoutItem(ctx context.Context, arg GetWorkoutItemParams) (WorkoutItem, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutItem, arg.ID, arg.UserID)
	var i WorkoutItem
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.ExerciseID,
		&i.Position,
		&i.TargetSets,
		&i.TargetReps,
		&i.TargetWeight,
		&i.TargetRestSeconds,
		&i.TargetDurationSeconds,
		&i.TargetDistanceMeters,
		&i.TargetAvgHeartRate,
		&i.TargetCalories,
	)
	return i, err
}

const getWorkoutItemContext = `-- name: GetWorkoutItemContext :one
SELECT w.id AS workout_id, wb.id AS block_id, wi.id AS workout_item_id FROM workout_items wi
JOIN workout_blocks wb ON wi.block_id = wb.id
JOIN workouts w ON wb.workout_id = w.id
WHERE wi.id = ? AND w.user_id = ?
`

type GetWorkoutItemContextParams struct {
	ID     string
	UserID string
}

type GetWorkoutItemContextRow struct {
	WorkoutID     string
	BlockID       string
	WorkoutItemID string
}

// Parentage of one workout item scoped to the user. Used to validate
// the exercise-entry logging triple (the item must belong to the
// workout the entry claims).
func (q *Queries) GetWorkoutItemContext(ctx context.Context, arg GetWorkoutItemContextParams) (GetWorkoutItemContextRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutItemContext, arg.ID, arg.UserID)
	var i GetWorkoutItemContextRow
	err := row.Scan(&i.WorkoutID, &i.BlockID, &i.WorkoutItemID)
	return i, err
}

const listWorkoutBlocks = `-- name: ListWorkoutBlocks :many
SELECT id, workout_id, type, position, rounds, rest_between_rounds_seconds, interval_seconds, time_cap_seconds FROM workout_blocks
WHERE workout_id = ?
ORDER BY position ASC
`

func (q *Queries) ListWorkoutBlocks(ctx context.Context, workoutID string) ([]WorkoutBlock, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutBlocks, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutBlock
	for rows.Next() {
		var i WorkoutBlock
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.Type,
			&i.Position,
			&i.Rounds,
			&i.RestBetweenRoundsSeconds,
			&i.IntervalSeconds,
			&i.TimeCapSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutItemsByWorkout = `-- name: ListWorkoutItemsByWorkout :many
SELECT wi.id, wi.block_id, wi.exercise_id, wi.position, wi.target_sets, wi.target_reps, wi.target_weight, wi.target_rest_seconds, wi.target_duration_seconds, wi.target_distance_meters, wi.target_avg_heart_rate, wi.target_calories FROM workout_items wi
JOIN workout_blocks wb ON wi.block_id = wb.id
WHERE wb.workout_id = ?
ORDER BY wb.position ASC, wi.position ASC
`

func (q *Queries) ListWorkoutItemsByWorkout(ctx context.Context, workoutID string) ([]WorkoutItem, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutItemsByWorkout, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutItem
	for rows.Next() {
		var i WorkoutItem
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.ExerciseID,
			&i.Position,
			&i.TargetSets,
			&i.TargetReps,
			&i.TargetWeight,
			&i.TargetRestSeconds,
			&i.TargetDurationSeconds,
			&i.TargetDistanceMeters,
			&i.TargetAvgHeartRate,
			&i.TargetCalories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutItemsByWorkoutWithExercises = `-- name: ListWorkoutItemsByWorkoutWithExercises :many
SELECT wi.id, wi.block_id, wi.exercise_id, wi.position, wi.target_sets, wi.target_reps, wi.target_weight, wi.target_rest_seconds, wi.target_duration_seconds, wi.target_distance_meters, wi.target_avg_heart_rate, wi.target_calories, e.name AS exercise_name, e.type AS exercise_type FROM workout_items wi
JOIN workout_blocks wb ON wi.block_id = wb.id
JOIN exercises e ON wi.exercise_id = e.id
WHERE wb.workout_id = ?
ORDER BY wb.position ASC, wi.position ASC
`

type ListWorkoutItemsByWorkoutWithExercisesRow struct {
	ID                    string
	BlockID               string
	ExerciseID            string
	Position              int64
	TargetSets            int64
	TargetReps            int64
	TargetWeight          float64
	TargetRestSeconds     int64
	TargetDurationSeconds int64
	TargetDistanceMeters  float64
	TargetAvgHeartRate    int64
	TargetCalories        float64
	ExerciseName          string
	ExerciseType          string
}

// Workout items with their exercise catalogue names and types so
// detail reads do not need a lookup per item.
func (q *Queries) ListWorkoutItemsByWorkoutWithExercises(ctx context.Context, workoutID string) ([]ListWorkoutItemsByWorkoutWithExercisesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutItemsByWorkoutWithExercises, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutItemsByWorkoutWithExercisesRow
	for rows.Next() {
		var i ListWorkoutItemsByWorkoutWithExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.ExerciseID,
			&i.Position,
			&i.TargetSets,
			&i.TargetReps,
			&i.TargetWeight,
			&i.TargetRestSeconds,
			&i.TargetDurationSeconds,
			&i.TargetDistanceMeters,
			&i.TargetAvgHeartRate,
			&i.TargetCalories,
			&i.ExerciseName,
			&i.ExerciseType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT id, user_id, source_workout_id, name, notes, status, scheduled_start, scheduled_end, completed_at, created_at, updated_at FROM workouts
WHERE user_id = ?
ORDER BY CASE WHEN status = 'planned' THEN 0 ELSE 1 END, CASE WHEN scheduled_start IS NULL THEN 1 ELSE 0 END, scheduled_start ASC, created_at DESC
`

// Planned first (scheduled_start ascending, unscheduled last), then by
// recency. The CASE emulates NULLS LAST for scheduled_start.
func (q *Queries) ListWorkouts(ctx context.Context, userID string) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceWorkoutID,
			&i.Name,
			&i.Notes,
			&i.Status,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsByRange = `-- name: ListWorkoutsByRange :many
SELECT id, user_id, source_workout_id, name, notes, status, scheduled_start, scheduled_end, completed_at, created_at, updated_at FROM workouts
WHERE user_id = ?
  AND status != 'cancelled'
  AND scheduled_start IS NOT NULL
  AND scheduled_start <= ?
  AND (scheduled_end IS NULL OR scheduled_end >= ?)
ORDER BY scheduled_start ASC
`

type ListWorkoutsByRangeParams struct {
	UserID         string
	ScheduledStart sql.NullTime
	ScheduledEnd   sql.NullTime
}

// Workouts whose scheduled window overlaps the given range.
// Unscheduled rows (scheduled_start IS NULL) are excluded -- they
// surface in ListWorkouts. Cancelled workouts are excluded so
// cancelling genuinely clears the calendar.
func (q *Queries) ListWorkoutsByRange(ctx context.Context, arg ListWorkoutsByRangeParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutsByRange, arg.UserID, arg.ScheduledStart, arg.ScheduledEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceWorkoutID,
			&i.Name,
			&i.Notes,
			&i.Status,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkoutStatus = `-- name: SetWorkoutStatus :exec
UPDATE workouts
SET status = ?,
    completed_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type SetWorkoutStatusParams struct {
	Status      string
	CompletedAt sql.NullTime
	ID          string
	UserID      string
}

// completed_at is managed by the caller: set on complete, cleared on
// reopen/cancel so status changes own the timestamp (same pattern as goals).
func (q *Queries) SetWorkoutStatus(ctx context.Context, arg SetWorkoutStatusParams) error {
	_, err := q.db.ExecContext(ctx, setWorkoutStatus,
		arg.Status,
		arg.CompletedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateWorkout = `-- name: UpdateWorkout :exec
UPDATE workouts
SET name = ?,
    notes = ?,
    scheduled_start = ?,
    scheduled_end = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateWorkoutParams struct {
	Name           string
	Notes          sql.NullString
	ScheduledStart sql.NullTime
	ScheduledEnd   sql.NullTime
	ID             string
	UserID         string
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkout,
		arg.Name,
		arg.Notes,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.ID,
		arg.UserID,
	)
	return err
}
