// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workouts.sql

package db

import (
	"context"
	"time"
)

const countWorkoutsUsingBlock = `-- name: CountWorkoutsUsingBlock :one
SELECT COUNT(*) AS use_count
FROM workout_blocks wb
JOIN workouts w ON w.id = wb.workout_id
WHERE wb.block_id = ? AND w.user_id = ?
`

type CountWorkoutsUsingBlockParams struct {
	BlockID string
	UserID  string
}

// Guards block deletion: a block referenced by any of the user's
// workouts is rejected with a 409 instead of being silently
// unlinked. Scoped to the user via the workouts join.
func (q *Queries) CountWorkoutsUsingBlock(ctx context.Context, arg CountWorkoutsUsingBlockParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkoutsUsingBlock, arg.BlockID, arg.UserID)
	var use_count int64
	err := row.Scan(&use_count)
	return use_count, err
}

const createWorkout = `-- name: CreateWorkout :one

INSERT INTO workouts (id, user_id, name, description, scheduled_date, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, description, scheduled_date, status, created_at, updated_at
`

type CreateWorkoutParams struct {
	ID            string
	UserID        string
	Name          string
	Description   string
	ScheduledDate string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Workouts are user-owned scheduled collections of blocks. Every
// query is scoped to user_id (via the workouts row) so a request can
// never read or mutate another user's training schedule.
func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ScheduledDate,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ScheduledDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkoutBlock = `-- name: CreateWorkoutBlock :one
INSERT INTO workout_blocks (id, workout_id, block_id, position, status, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, workout_id, block_id, position, status, created_at
`

type CreateWorkoutBlockParams struct {
	ID        string
	WorkoutID string
	BlockID   string
	Position  int64
	Status    string
	CreatedAt time.Time
}

func (q *Queries) CreateWorkoutBlock(ctx context.Context, arg CreateWorkoutBlockParams) (WorkoutBlock, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutBlock,
		arg.ID,
		arg.WorkoutID,
		arg.BlockID,
		arg.Position,
		arg.Status,
		arg.CreatedAt,
	)
	var i WorkoutBlock
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.BlockID,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts
WHERE id = ? AND user_id = ?
`

type DeleteWorkoutParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkout, arg.ID, arg.UserID)
	return err
}

const deleteWorkoutBlocks = `-- name: DeleteWorkoutBlocks :exec
DELETE FROM workout_blocks
WHERE workout_id = ?
`

// Full block replacement on update: delete-all then re-insert in a
// transaction (the repository owns the tx). Also keeps deletes
// correct on databases ignoring ON DELETE CASCADE.
func (q *Queries) DeleteWorkoutBlocks(ctx context.Context, workoutID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutBlocks, workoutID)
	return err
}

const getWorkout = `-- name: GetWorkout :one
SELECT id, user_id, name, description, scheduled_date, status, created_at, updated_at FROM workouts
WHERE id = ? AND user_id = ?
`

type GetWorkoutParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetWorkout(ctx context.Context, arg GetWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkout, arg.ID, arg.UserID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ScheduledDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutBlock = `-- name: GetWorkoutBlock :one
SELECT id, workout_id, block_id, position, status, created_at FROM workout_blocks
WHERE id = ? AND workout_id = ?
`

type GetWorkoutBlockParams struct {
	ID        string
	WorkoutID string
}

func (q *Queries) GetWorkoutBlock(ctx context.Context, arg GetWorkoutBlockParams) (WorkoutBlock, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutBlock, arg.ID, arg.WorkoutID)
	var i WorkoutBlock
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.BlockID,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkoutBlocks = `-- name: ListWorkoutBlocks :many
SELECT id, workout_id, block_id, position, status, created_at FROM workout_blocks
WHERE workout_id = ?
ORDER BY position ASC
`

func (q *Queries) ListWorkoutBlocks(ctx context.Context, workoutID string) ([]WorkoutBlock, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutBlocks, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutBlock
	for rows.Next() {
		var i WorkoutBlock
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.BlockID,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutBlocksWithBlock = `-- name: ListWorkoutBlocksWithBlock :many
SELECT wb.id, wb.workout_id, wb.block_id, wb.position, wb.status, wb.created_at,
       b.name AS block_name, b.description AS block_description, b.block_type AS block_type,
       COUNT(i.id) AS item_count
FROM workout_blocks wb
JOIN blocks b ON b.id = wb.block_id
LEFT JOIN block_items i ON i.block_id = b.id
WHERE wb.workout_id = ?
GROUP BY wb.id
ORDER BY wb.position ASC
`

type ListWorkoutBlocksWithBlockRow struct {
	ID               string
	WorkoutID        string
	BlockID          string
	Position         int64
	Status           string
	CreatedAt        time.Time
	BlockName        string
	BlockDescription string
	BlockType        string
	ItemCount        int64
}

// Detail view resolves each planned block to its name/type plus
// item count in one query. Ownership is gated by the caller's prior
// GetWorkout (scoped to user_id); this query only orders the rows.
func (q *Queries) ListWorkoutBlocksWithBlock(ctx context.Context, workoutID string) ([]ListWorkoutBlocksWithBlockRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutBlocksWithBlock, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutBlocksWithBlockRow
	for rows.Next() {
		var i ListWorkoutBlocksWithBlockRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.BlockID,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
			&i.BlockName,
			&i.BlockDescription,
			&i.BlockType,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT id, user_id, name, description, scheduled_date, status, created_at, updated_at FROM workouts
WHERE user_id = ?
ORDER BY scheduled_date DESC, created_at DESC, rowid DESC
`

// Newest scheduled date first; rowid breaks ties (same convention
// as exercise_entries ordering).
func (q *Queries) ListWorkouts(ctx context.Context, userID string) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ScheduledDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsInRange = `-- name: ListWorkoutsInRange :many
SELECT id, user_id, name, description, scheduled_date, status, created_at, updated_at FROM workouts
WHERE user_id = ? AND scheduled_date >= ? AND scheduled_date <= ?
ORDER BY scheduled_date ASC, created_at ASC, rowid ASC
`

type ListWorkoutsInRangeParams struct {
	UserID          string
	ScheduledDate   string
	ScheduledDate_2 string
}

// Schedule views (e.g. the dashboard calendar week) fetch one
// inclusive date range. scheduled_date is YYYY-MM-DD so lexical
// comparison is chronological.
func (q *Queries) ListWorkoutsInRange(ctx context.Context, arg ListWorkoutsInRangeParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutsInRange, arg.UserID, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ScheduledDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsInRangeWithBlockCounts = `-- name: ListWorkoutsInRangeWithBlockCounts :many
SELECT w.id, w.user_id, w.name, w.description, w.scheduled_date, w.status, w.created_at, w.updated_at,
       COUNT(wb.id) AS block_count,
       COUNT(CASE WHEN wb.status = 'done' THEN 1 END) AS done_count
FROM workouts w
LEFT JOIN workout_blocks wb ON wb.workout_id = w.id
WHERE w.user_id = ? AND w.scheduled_date >= ? AND w.scheduled_date <= ?
GROUP BY w.id
ORDER BY w.scheduled_date ASC, w.created_at ASC, w.rowid ASC
`

type ListWorkoutsInRangeWithBlockCountsParams struct {
	UserID          string
	ScheduledDate   string
	ScheduledDate_2 string
}

type ListWorkoutsInRangeWithBlockCountsRow struct {
	ID            string
	UserID        string
	Name          string
	Description   string
	ScheduledDate string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	BlockCount    int64
	DoneCount     int64
}

// Range variant of the list view (calendar weeks).
func (q *Queries) ListWorkoutsInRangeWithBlockCounts(ctx context.Context, arg ListWorkoutsInRangeWithBlockCountsParams) ([]ListWorkoutsInRangeWithBlockCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutsInRangeWithBlockCounts, arg.UserID, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutsInRangeWithBlockCountsRow
	for rows.Next() {
		var i ListWorkoutsInRangeWithBlockCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ScheduledDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockCount,
			&i.DoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsWithBlockCounts = `-- name: ListWorkoutsWithBlockCounts :many
SELECT w.id, w.user_id, w.name, w.description, w.scheduled_date, w.status, w.created_at, w.updated_at,
       COUNT(wb.id) AS block_count,
       COUNT(CASE WHEN wb.status = 'done' THEN 1 END) AS done_count
FROM workouts w
LEFT JOIN workout_blocks wb ON wb.workout_id = w.id
WHERE w.user_id = ?
GROUP BY w.id
ORDER BY w.scheduled_date DESC, w.created_at DESC, w.rowid DESC
`

type ListWorkoutsWithBlockCountsRow struct {
	ID            string
	UserID        string
	Name          string
	Description   string
	ScheduledDate string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	BlockCount    int64
	DoneCount     int64
}

// List view needs per-workout block + done counts without N+1.
func (q *Queries) ListWorkoutsWithBlockCounts(ctx context.Context, userID string) ([]ListWorkoutsWithBlockCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutsWithBlockCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutsWithBlockCountsRow
	for rows.Next() {
		var i ListWorkoutsWithBlockCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ScheduledDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockCount,
			&i.DoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkout = `-- name: UpdateWorkout :exec
UPDATE workouts
SET name = ?,
    description = ?,
    scheduled_date = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateWorkoutParams struct {
	Name          string
	Description   string
	ScheduledDate string
	Status        string
	ID            string
	UserID        string
}

// Overwrites the editable workout fields and bumps updated_at.
// Blocks are replaced separately via DeleteWorkoutBlocks +
// CreateWorkoutBlock.
func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkout,
		arg.Name,
		arg.Description,
		arg.ScheduledDate,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateWorkoutBlockStatus = `-- name: UpdateWorkoutBlockStatus :exec
UPDATE workout_blocks
SET status = ?
WHERE id = ? AND workout_id = ?
`

type UpdateWorkoutBlockStatusParams struct {
	Status    string
	ID        string
	WorkoutID string
}

func (q *Queries) UpdateWorkoutBlockStatus(ctx context.Context, arg UpdateWorkoutBlockStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkoutBlockStatus, arg.Status, arg.ID, arg.WorkoutID)
	return err
}
